// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Cmd.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cmd_Priority int32

const (
	Cmd_LOW         Cmd_Priority = 0
	Cmd_DEFAULT     Cmd_Priority = 1
	Cmd_HIGH        Cmd_Priority = 2
	Cmd_IMMEDIATELY Cmd_Priority = 3
)

var Cmd_Priority_name = map[int32]string{
	0: "LOW",
	1: "DEFAULT",
	2: "HIGH",
	3: "IMMEDIATELY",
}
var Cmd_Priority_value = map[string]int32{
	"LOW":         0,
	"DEFAULT":     1,
	"HIGH":        2,
	"IMMEDIATELY": 3,
}

func (x Cmd_Priority) String() string {
	return proto.EnumName(Cmd_Priority_name, int32(x))
}
func (Cmd_Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{0, 0}
}

type Cmd_Status int32

const (
	Cmd_WAITING Cmd_Status = 0
	Cmd_SUCCESS Cmd_Status = 1
	Cmd_FAIL    Cmd_Status = 2
)

var Cmd_Status_name = map[int32]string{
	0: "WAITING",
	1: "SUCCESS",
	2: "FAIL",
}
var Cmd_Status_value = map[string]int32{
	"WAITING": 0,
	"SUCCESS": 1,
	"FAIL":    2,
}

func (x Cmd_Status) String() string {
	return proto.EnumName(Cmd_Status_name, int32(x))
}
func (Cmd_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{0, 1}
}

type Cmd struct {
	Cid               string       `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Cname             string       `protobuf:"bytes,2,opt,name=cname,proto3" json:"cname,omitempty"`
	Wid               int64        `protobuf:"varint,3,opt,name=wid,proto3" json:"wid,omitempty"`
	Data              []byte       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ExtraInfo         []byte       `protobuf:"bytes,5,opt,name=extraInfo,proto3" json:"extraInfo,omitempty"`
	DelayMillis       int64        `protobuf:"varint,6,opt,name=delayMillis,proto3" json:"delayMillis,omitempty"`
	Priority          Cmd_Priority `protobuf:"varint,7,opt,name=priority,proto3,enum=proto.Cmd_Priority" json:"priority,omitempty"`
	RetryTimes        int32        `protobuf:"varint,8,opt,name=retryTimes,proto3" json:"retryTimes,omitempty"`
	CurrentRetryTimes int32        `protobuf:"varint,9,opt,name=currentRetryTimes,proto3" json:"currentRetryTimes,omitempty"`
	Timestamp         int64        `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Timeout           int64        `protobuf:"varint,11,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// code msg 仅在客户端应答时有值
	Code int32  `protobuf:"varint,12,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,13,opt,name=msg,proto3" json:"msg,omitempty"`
	// status 仅本地使用
	Status               Cmd_Status `protobuf:"varint,14,opt,name=status,proto3,enum=proto.Cmd_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{0}
}
func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (dst *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(dst, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Cmd) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *Cmd) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Cmd) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Cmd) GetExtraInfo() []byte {
	if m != nil {
		return m.ExtraInfo
	}
	return nil
}

func (m *Cmd) GetDelayMillis() int64 {
	if m != nil {
		return m.DelayMillis
	}
	return 0
}

func (m *Cmd) GetPriority() Cmd_Priority {
	if m != nil {
		return m.Priority
	}
	return Cmd_LOW
}

func (m *Cmd) GetRetryTimes() int32 {
	if m != nil {
		return m.RetryTimes
	}
	return 0
}

func (m *Cmd) GetCurrentRetryTimes() int32 {
	if m != nil {
		return m.CurrentRetryTimes
	}
	return 0
}

func (m *Cmd) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Cmd) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Cmd) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Cmd) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Cmd) GetStatus() Cmd_Status {
	if m != nil {
		return m.Status
	}
	return Cmd_WAITING
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{1}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{2}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

// 登录
type CmdWw321 struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw321) Reset()         { *m = CmdWw321{} }
func (m *CmdWw321) String() string { return proto.CompactTextString(m) }
func (*CmdWw321) ProtoMessage()    {}
func (*CmdWw321) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{3}
}
func (m *CmdWw321) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw321.Unmarshal(m, b)
}
func (m *CmdWw321) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw321.Marshal(b, m, deterministic)
}
func (dst *CmdWw321) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw321.Merge(dst, src)
}
func (m *CmdWw321) XXX_Size() int {
	return xxx_messageInfo_CmdWw321.Size(m)
}
func (m *CmdWw321) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw321.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw321 proto.InternalMessageInfo

func (m *CmdWw321) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 注销
type CmdWw322 struct {
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw322) Reset()         { *m = CmdWw322{} }
func (m *CmdWw322) String() string { return proto.CompactTextString(m) }
func (*CmdWw322) ProtoMessage()    {}
func (*CmdWw322) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{4}
}
func (m *CmdWw322) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw322.Unmarshal(m, b)
}
func (m *CmdWw322) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw322.Marshal(b, m, deterministic)
}
func (dst *CmdWw322) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw322.Merge(dst, src)
}
func (m *CmdWw322) XXX_Size() int {
	return xxx_messageInfo_CmdWw322.Size(m)
}
func (m *CmdWw322) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw322.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw322 proto.InternalMessageInfo

func (m *CmdWw322) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Cmd323 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd323) Reset()         { *m = Cmd323{} }
func (m *Cmd323) String() string { return proto.CompactTextString(m) }
func (*Cmd323) ProtoMessage()    {}
func (*Cmd323) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{5}
}
func (m *Cmd323) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd323.Unmarshal(m, b)
}
func (m *Cmd323) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd323.Marshal(b, m, deterministic)
}
func (dst *Cmd323) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd323.Merge(dst, src)
}
func (m *Cmd323) XXX_Size() int {
	return xxx_messageInfo_Cmd323.Size(m)
}
func (m *Cmd323) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd323.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd323 proto.InternalMessageInfo

type Cmd324 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd324) Reset()         { *m = Cmd324{} }
func (m *Cmd324) String() string { return proto.CompactTextString(m) }
func (*Cmd324) ProtoMessage()    {}
func (*Cmd324) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{6}
}
func (m *Cmd324) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd324.Unmarshal(m, b)
}
func (m *Cmd324) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd324.Marshal(b, m, deterministic)
}
func (dst *Cmd324) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd324.Merge(dst, src)
}
func (m *Cmd324) XXX_Size() int {
	return xxx_messageInfo_Cmd324.Size(m)
}
func (m *Cmd324) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd324.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd324 proto.InternalMessageInfo

type Cmd325 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd325) Reset()         { *m = Cmd325{} }
func (m *Cmd325) String() string { return proto.CompactTextString(m) }
func (*Cmd325) ProtoMessage()    {}
func (*Cmd325) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{7}
}
func (m *Cmd325) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd325.Unmarshal(m, b)
}
func (m *Cmd325) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd325.Marshal(b, m, deterministic)
}
func (dst *Cmd325) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd325.Merge(dst, src)
}
func (m *Cmd325) XXX_Size() int {
	return xxx_messageInfo_Cmd325.Size(m)
}
func (m *Cmd325) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd325.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd325 proto.InternalMessageInfo

type Cmd326 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd326) Reset()         { *m = Cmd326{} }
func (m *Cmd326) String() string { return proto.CompactTextString(m) }
func (*Cmd326) ProtoMessage()    {}
func (*Cmd326) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_eedcd5a9995bc6da, []int{8}
}
func (m *Cmd326) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd326.Unmarshal(m, b)
}
func (m *Cmd326) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd326.Marshal(b, m, deterministic)
}
func (dst *Cmd326) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd326.Merge(dst, src)
}
func (m *Cmd326) XXX_Size() int {
	return xxx_messageInfo_Cmd326.Size(m)
}
func (m *Cmd326) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd326.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd326 proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Cmd)(nil), "proto.Cmd")
	proto.RegisterType((*Ping)(nil), "proto.Ping")
	proto.RegisterType((*Pong)(nil), "proto.Pong")
	proto.RegisterType((*CmdWw321)(nil), "proto.CmdWw321")
	proto.RegisterType((*CmdWw322)(nil), "proto.CmdWw322")
	proto.RegisterType((*Cmd323)(nil), "proto.Cmd323")
	proto.RegisterType((*Cmd324)(nil), "proto.Cmd324")
	proto.RegisterType((*Cmd325)(nil), "proto.Cmd325")
	proto.RegisterType((*Cmd326)(nil), "proto.Cmd326")
	proto.RegisterEnum("proto.Cmd_Priority", Cmd_Priority_name, Cmd_Priority_value)
	proto.RegisterEnum("proto.Cmd_Status", Cmd_Status_name, Cmd_Status_value)
}

func init() { proto.RegisterFile("Cmd.proto", fileDescriptor_Cmd_eedcd5a9995bc6da) }

var fileDescriptor_Cmd_eedcd5a9995bc6da = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xf1, 0x47, 0x9c, 0x49, 0x29, 0xee, 0xc2, 0x61, 0x85, 0x50, 0x65, 0x99, 0x8b, 0x91,
	0x2a, 0x23, 0x12, 0xe0, 0xc2, 0x29, 0x75, 0xd3, 0xd6, 0x52, 0x02, 0x91, 0x93, 0x2a, 0xe2, 0xe8,
	0x7a, 0x17, 0x6b, 0x85, 0xd7, 0x8e, 0xd6, 0x1b, 0x95, 0xfc, 0x01, 0x7e, 0x37, 0xda, 0x75, 0xe3,
	0x58, 0xe2, 0xb4, 0x6f, 0xde, 0x7b, 0x33, 0x9a, 0x99, 0x1d, 0x18, 0xc5, 0x9c, 0x44, 0x3b, 0x51,
	0xcb, 0x1a, 0xd9, 0xfa, 0x09, 0xfe, 0x5a, 0x60, 0xc6, 0x9c, 0x20, 0x0f, 0xcc, 0x9c, 0x11, 0x6c,
	0xf8, 0x46, 0x38, 0x4a, 0x15, 0x44, 0x6f, 0xc0, 0xce, 0xab, 0x8c, 0x53, 0x3c, 0xd0, 0x5c, 0x1b,
	0x28, 0xdf, 0x13, 0x23, 0xd8, 0xf4, 0x8d, 0xd0, 0x4c, 0x15, 0x44, 0x08, 0x2c, 0x92, 0xc9, 0x0c,
	0x5b, 0xbe, 0x11, 0x9e, 0xa5, 0x1a, 0xa3, 0x77, 0x30, 0xa2, 0x7f, 0xa4, 0xc8, 0x92, 0xea, 0x57,
	0x8d, 0x6d, 0x2d, 0x9c, 0x08, 0xe4, 0xc3, 0x98, 0xd0, 0x32, 0x3b, 0x2c, 0x59, 0x59, 0xb2, 0x06,
	0x3b, 0xba, 0x56, 0x9f, 0x42, 0x1f, 0xc1, 0xdd, 0x09, 0x56, 0x0b, 0x26, 0x0f, 0x78, 0xe8, 0x1b,
	0xe1, 0xf9, 0xe4, 0x75, 0xdb, 0x76, 0xa4, 0x06, 0x58, 0x3d, 0x4b, 0x69, 0x67, 0x42, 0x97, 0x00,
	0x82, 0x4a, 0x71, 0xd8, 0x30, 0x4e, 0x1b, 0xec, 0xfa, 0x46, 0x68, 0xa7, 0x3d, 0x06, 0x5d, 0xc1,
	0x45, 0xbe, 0x17, 0x82, 0x56, 0x32, 0x3d, 0xd9, 0x46, 0xda, 0xf6, 0xbf, 0xa0, 0xda, 0x97, 0x0a,
	0xc8, 0x8c, 0xef, 0x30, 0xe8, 0xf6, 0x4e, 0x04, 0xc2, 0x30, 0x54, 0x41, 0xbd, 0x97, 0x78, 0xac,
	0xb5, 0x63, 0xa8, 0x56, 0x91, 0xd7, 0x84, 0xe2, 0x33, 0x5d, 0x58, 0x63, 0xb5, 0x30, 0xde, 0x14,
	0xf8, 0x65, 0xbb, 0x58, 0xde, 0x14, 0xe8, 0x03, 0x38, 0x8d, 0xcc, 0xe4, 0xbe, 0xc1, 0xe7, 0x7a,
	0xb4, 0x8b, 0xde, 0x68, 0x6b, 0x2d, 0xa4, 0xcf, 0x86, 0xe0, 0x1b, 0xb8, 0xc7, 0x61, 0xd1, 0x10,
	0xcc, 0xc5, 0x8f, 0xad, 0xf7, 0x02, 0x8d, 0x61, 0x78, 0x33, 0xbf, 0x9d, 0x3d, 0x2c, 0x36, 0x9e,
	0x81, 0x5c, 0xb0, 0xee, 0x93, 0xbb, 0x7b, 0x6f, 0x80, 0x5e, 0xc1, 0x38, 0x59, 0x2e, 0xe7, 0x37,
	0xc9, 0x6c, 0x33, 0x5f, 0xfc, 0xf4, 0xcc, 0xe0, 0x0a, 0x9c, 0xb6, 0x9c, 0xca, 0xd8, 0xce, 0x92,
	0x4d, 0xf2, 0xfd, 0xae, 0x4d, 0x5f, 0x3f, 0xc4, 0xf1, 0x7c, 0xbd, 0x6e, 0xd3, 0x6f, 0x67, 0xc9,
	0xc2, 0x1b, 0x04, 0x0e, 0x58, 0x2b, 0x56, 0x15, 0xfa, 0xad, 0xab, 0x22, 0xb8, 0x04, 0x37, 0xe6,
	0x64, 0xfb, 0x34, 0x9d, 0x7c, 0xea, 0xbe, 0xb8, 0xbd, 0x0e, 0x8d, 0x7b, 0xfa, 0xa4, 0xd3, 0xcd,
	0x9e, 0xee, 0x82, 0x13, 0x73, 0x32, 0x9d, 0x4c, 0x3b, 0xf4, 0xb9, 0x43, 0x5f, 0x3a, 0xf4, 0xf5,
	0xfa, 0x3d, 0xbc, 0xcd, 0x6b, 0x1e, 0xf1, 0xac, 0x60, 0x79, 0xf4, 0x9b, 0x8a, 0x8a, 0x96, 0x51,
	0x7e, 0xbc, 0xd2, 0x6b, 0x3b, 0xe6, 0x64, 0xf5, 0xf8, 0xe8, 0xe8, 0x68, 0xfa, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x6e, 0x3d, 0x36, 0x4a, 0xc0, 0x02, 0x00, 0x00,
}
