// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Cmd.proto

package proto_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cmd_Priority int32

const (
	Cmd_LOW         Cmd_Priority = 0
	Cmd_DEFAULT     Cmd_Priority = 1
	Cmd_HIGH        Cmd_Priority = 2
	Cmd_IMMEDIATELY Cmd_Priority = 3
)

var Cmd_Priority_name = map[int32]string{
	0: "LOW",
	1: "DEFAULT",
	2: "HIGH",
	3: "IMMEDIATELY",
}
var Cmd_Priority_value = map[string]int32{
	"LOW":         0,
	"DEFAULT":     1,
	"HIGH":        2,
	"IMMEDIATELY": 3,
}

func (x Cmd_Priority) String() string {
	return proto.EnumName(Cmd_Priority_name, int32(x))
}
func (Cmd_Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_78a7ad54aa03f7ed, []int{0, 0}
}

type Cmd_Status int32

const (
	Cmd_INIT Cmd_Status = 0
	Cmd_DONE Cmd_Status = 1
	Cmd_FAIL Cmd_Status = 2
)

var Cmd_Status_name = map[int32]string{
	0: "INIT",
	1: "DONE",
	2: "FAIL",
}
var Cmd_Status_value = map[string]int32{
	"INIT": 0,
	"DONE": 1,
	"FAIL": 2,
}

func (x Cmd_Status) String() string {
	return proto.EnumName(Cmd_Status_name, int32(x))
}
func (Cmd_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_78a7ad54aa03f7ed, []int{0, 1}
}

type Cmd struct {
	Cid                  string       `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Cname                string       `protobuf:"bytes,2,opt,name=cname,proto3" json:"cname,omitempty"`
	Wid                  int64        `protobuf:"varint,3,opt,name=wid,proto3" json:"wid,omitempty"`
	Data                 []byte       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ExtraInfo            []byte       `protobuf:"bytes,5,opt,name=extraInfo,proto3" json:"extraInfo,omitempty"`
	DelayMillis          int64        `protobuf:"varint,6,opt,name=delayMillis,proto3" json:"delayMillis,omitempty"`
	Priority             Cmd_Priority `protobuf:"varint,7,opt,name=priority,proto3,enum=proto_pb.Cmd_Priority" json:"priority,omitempty"`
	Timestamp            int64        `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status               int32        `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string       `protobuf:"bytes,10,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_78a7ad54aa03f7ed, []int{0}
}
func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (dst *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(dst, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Cmd) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *Cmd) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Cmd) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Cmd) GetExtraInfo() []byte {
	if m != nil {
		return m.ExtraInfo
	}
	return nil
}

func (m *Cmd) GetDelayMillis() int64 {
	if m != nil {
		return m.DelayMillis
	}
	return 0
}

func (m *Cmd) GetPriority() Cmd_Priority {
	if m != nil {
		return m.Priority
	}
	return Cmd_LOW
}

func (m *Cmd) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Cmd) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Cmd) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_78a7ad54aa03f7ed, []int{1}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_Cmd_78a7ad54aa03f7ed, []int{2}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Cmd)(nil), "proto_pb.Cmd")
	proto.RegisterType((*Ping)(nil), "proto_pb.Ping")
	proto.RegisterType((*Pong)(nil), "proto_pb.Pong")
	proto.RegisterEnum("proto_pb.Cmd_Priority", Cmd_Priority_name, Cmd_Priority_value)
	proto.RegisterEnum("proto_pb.Cmd_Status", Cmd_Status_name, Cmd_Status_value)
}

func init() { proto.RegisterFile("Cmd.proto", fileDescriptor_Cmd_78a7ad54aa03f7ed) }

var fileDescriptor_Cmd_78a7ad54aa03f7ed = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x4f, 0x4d, 0x6f, 0x9b, 0x40,
	0x14, 0x34, 0x9f, 0x86, 0xe7, 0xaa, 0x45, 0xab, 0xca, 0xda, 0x43, 0x0f, 0x08, 0x55, 0x15, 0x97,
	0x72, 0x70, 0x8f, 0x3d, 0xf9, 0x03, 0xc7, 0x48, 0xf8, 0x43, 0xc4, 0x51, 0x94, 0x53, 0xb4, 0x06,
	0x42, 0x56, 0x66, 0x59, 0x04, 0x1b, 0x25, 0xfe, 0xdf, 0xf9, 0x01, 0x11, 0x8b, 0x1d, 0xe7, 0xf4,
	0x66, 0xe6, 0xcd, 0xce, 0xbe, 0x01, 0x7b, 0xce, 0xb2, 0xa0, 0x6e, 0xb8, 0xe0, 0xc8, 0x92, 0xe3,
	0xb1, 0x3e, 0x78, 0xef, 0x2a, 0x68, 0x73, 0x96, 0x21, 0x07, 0xb4, 0x94, 0x66, 0x58, 0x71, 0x15,
	0xdf, 0x4e, 0x3a, 0x88, 0x7e, 0x82, 0x91, 0x56, 0x84, 0xe5, 0x58, 0x95, 0x5a, 0x4f, 0x3a, 0xdf,
	0x2b, 0xcd, 0xb0, 0xe6, 0x2a, 0xbe, 0x96, 0x74, 0x10, 0x21, 0xd0, 0x33, 0x22, 0x08, 0xd6, 0x5d,
	0xc5, 0xff, 0x96, 0x48, 0x8c, 0x7e, 0x81, 0x9d, 0xbf, 0x89, 0x86, 0x44, 0xd5, 0x13, 0xc7, 0x86,
	0x5c, 0x5c, 0x05, 0xe4, 0xc2, 0x28, 0xcb, 0x4b, 0x72, 0x5a, 0xd3, 0xb2, 0xa4, 0x2d, 0x36, 0x65,
	0xd6, 0x57, 0x09, 0x4d, 0xc0, 0xaa, 0x1b, 0xca, 0x1b, 0x2a, 0x4e, 0x78, 0xe8, 0x2a, 0xfe, 0xf7,
	0xc9, 0x38, 0xb8, 0x9c, 0x1c, 0x74, 0x35, 0x76, 0xe7, 0x6d, 0xf2, 0xe9, 0xeb, 0xfe, 0x14, 0x94,
	0xe5, 0xad, 0x20, 0xac, 0xc6, 0x96, 0xcc, 0xbc, 0x0a, 0x68, 0x0c, 0x66, 0x2b, 0x88, 0x78, 0x69,
	0xb1, 0xed, 0x2a, 0xbe, 0x91, 0x9c, 0x59, 0xd7, 0x87, 0xb5, 0x05, 0x86, 0xbe, 0x37, 0x6b, 0x0b,
	0xef, 0x3f, 0x58, 0x97, 0x74, 0x34, 0x04, 0x2d, 0xde, 0xde, 0x3b, 0x03, 0x34, 0x82, 0xe1, 0x22,
	0x5c, 0x4e, 0xef, 0xe2, 0xbd, 0xa3, 0x20, 0x0b, 0xf4, 0x55, 0x74, 0xb3, 0x72, 0x54, 0xf4, 0x03,
	0x46, 0xd1, 0x7a, 0x1d, 0x2e, 0xa2, 0xe9, 0x3e, 0x8c, 0x1f, 0x1c, 0xcd, 0xfb, 0x03, 0xe6, 0x6d,
	0x1f, 0x6c, 0x81, 0x1e, 0x6d, 0xa2, 0xbd, 0x33, 0xe8, 0xd0, 0x62, 0xbb, 0x09, 0xfb, 0x87, 0xcb,
	0x69, 0x14, 0x3b, 0xaa, 0x67, 0x82, 0xbe, 0xa3, 0x55, 0x21, 0x27, 0xaf, 0x8a, 0xd9, 0x5f, 0xf8,
	0x9d, 0x72, 0x16, 0x30, 0x52, 0xd0, 0x34, 0x38, 0xe6, 0x4d, 0x95, 0x97, 0x01, 0x3f, 0x3e, 0x0b,
	0x51, 0x07, 0x2d, 0x4f, 0x8f, 0xb9, 0xe8, 0xeb, 0xcf, 0x8c, 0x39, 0xcb, 0x76, 0x87, 0x83, 0x29,
	0xd9, 0xbf, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x02, 0x93, 0xe7, 0xd3, 0x01, 0x00, 0x00,
}
