// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WwCmd.proto

package proto_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 会话类型
type Conversation_ConvType int32

const (
	Conversation_SINGLE Conversation_ConvType = 0
	Conversation_GROUP  Conversation_ConvType = 1
	Conversation_OTHER  Conversation_ConvType = 2
)

var Conversation_ConvType_name = map[int32]string{
	0: "SINGLE",
	1: "GROUP",
	2: "OTHER",
}
var Conversation_ConvType_value = map[string]int32{
	"SINGLE": 0,
	"GROUP":  1,
	"OTHER":  2,
}

func (x Conversation_ConvType) String() string {
	return proto.EnumName(Conversation_ConvType_name, int32(x))
}
func (Conversation_ConvType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{2, 0}
}

// 群类型
type Conversation_RoomType int32

const (
	Conversation_NORMAL     Conversation_RoomType = 0
	Conversation_ALL        Conversation_RoomType = 1
	Conversation_EXTERNAL   Conversation_RoomType = 2
	Conversation_DEPARTMENT Conversation_RoomType = 3
	Conversation_UNKNOWN    Conversation_RoomType = 4
	Conversation_BOT        Conversation_RoomType = 5
)

var Conversation_RoomType_name = map[int32]string{
	0: "NORMAL",
	1: "ALL",
	2: "EXTERNAL",
	3: "DEPARTMENT",
	4: "UNKNOWN",
	5: "BOT",
}
var Conversation_RoomType_value = map[string]int32{
	"NORMAL":     0,
	"ALL":        1,
	"EXTERNAL":   2,
	"DEPARTMENT": 3,
	"UNKNOWN":    4,
	"BOT":        5,
}

func (x Conversation_RoomType) String() string {
	return proto.EnumName(Conversation_RoomType_name, int32(x))
}
func (Conversation_RoomType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{2, 1}
}

type CmdWw336_OperateType int32

const (
	CmdWw336_AGREE  CmdWw336_OperateType = 0
	CmdWw336_REFUSE CmdWw336_OperateType = 1
	CmdWw336_LOOK   CmdWw336_OperateType = 2
)

var CmdWw336_OperateType_name = map[int32]string{
	0: "AGREE",
	1: "REFUSE",
	2: "LOOK",
}
var CmdWw336_OperateType_value = map[string]int32{
	"AGREE":  0,
	"REFUSE": 1,
	"LOOK":   2,
}

func (x CmdWw336_OperateType) String() string {
	return proto.EnumName(CmdWw336_OperateType_name, int32(x))
}
func (CmdWw336_OperateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{13, 0}
}

// ----------- 公用数据 ----------
type User struct {
	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname  string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Alias     string `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	AvatarUrl string `protobuf:"bytes,5,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	Gender    int64  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Phone     string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Mobile    string `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Acctid    string `protobuf:"bytes,9,opt,name=acctid,proto3" json:"acctid,omitempty"`
	// 企业用户有以下参数
	CorpId      int64  `protobuf:"varint,10,opt,name=corpId,proto3" json:"corpId,omitempty"`
	CorpName    string `protobuf:"bytes,11,opt,name=corpName,proto3" json:"corpName,omitempty"`
	CorpFName   string `protobuf:"bytes,12,opt,name=corpFName,proto3" json:"corpFName,omitempty"`
	CorpAddress string `protobuf:"bytes,13,opt,name=corpAddress,proto3" json:"corpAddress,omitempty"`
	Job         string `protobuf:"bytes,14,opt,name=job,proto3" json:"job,omitempty"`
	// 被他人添加时会有此值
	Apply                string   `protobuf:"bytes,15,opt,name=apply,proto3" json:"apply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetGender() int64 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetAcctid() string {
	if m != nil {
		return m.Acctid
	}
	return ""
}

func (m *User) GetCorpId() int64 {
	if m != nil {
		return m.CorpId
	}
	return 0
}

func (m *User) GetCorpName() string {
	if m != nil {
		return m.CorpName
	}
	return ""
}

func (m *User) GetCorpFName() string {
	if m != nil {
		return m.CorpFName
	}
	return ""
}

func (m *User) GetCorpAddress() string {
	if m != nil {
		return m.CorpAddress
	}
	return ""
}

func (m *User) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *User) GetApply() string {
	if m != nil {
		return m.Apply
	}
	return ""
}

type Department struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PartyId              int32    `protobuf:"varint,3,opt,name=partyId,proto3" json:"partyId,omitempty"`
	HasSon               bool     `protobuf:"varint,4,opt,name=hasSon,proto3" json:"hasSon,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	UserCount            int32    `protobuf:"varint,6,opt,name=userCount,proto3" json:"userCount,omitempty"`
	CorpId               int64    `protobuf:"varint,7,opt,name=corpId,proto3" json:"corpId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{1}
}
func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (dst *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(dst, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Department) GetPartyId() int32 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *Department) GetHasSon() bool {
	if m != nil {
		return m.HasSon
	}
	return false
}

func (m *Department) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Department) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *Department) GetCorpId() int64 {
	if m != nil {
		return m.CorpId
	}
	return 0
}

type Conversation struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl            string                `protobuf:"bytes,3,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	CreatorId            int64                 `protobuf:"varint,4,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	Exited               bool                  `protobuf:"varint,5,opt,name=exited,proto3" json:"exited,omitempty"`
	MemberCount          int32                 `protobuf:"varint,6,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	CreateTime           int64                 `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	ModifyTime           int64                 `protobuf:"varint,8,opt,name=modifyTime,proto3" json:"modifyTime,omitempty"`
	ConvType             Conversation_ConvType `protobuf:"varint,9,opt,name=convType,proto3,enum=proto_pb.Conversation_ConvType" json:"convType,omitempty"`
	RoomType             Conversation_RoomType `protobuf:"varint,10,opt,name=roomType,proto3,enum=proto_pb.Conversation_RoomType" json:"roomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{2}
}
func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (dst *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(dst, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Conversation) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Conversation) GetCreatorId() int64 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *Conversation) GetExited() bool {
	if m != nil {
		return m.Exited
	}
	return false
}

func (m *Conversation) GetMemberCount() int32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func (m *Conversation) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Conversation) GetModifyTime() int64 {
	if m != nil {
		return m.ModifyTime
	}
	return 0
}

func (m *Conversation) GetConvType() Conversation_ConvType {
	if m != nil {
		return m.ConvType
	}
	return Conversation_SINGLE
}

func (m *Conversation) GetRoomType() Conversation_RoomType {
	if m != nil {
		return m.RoomType
	}
	return Conversation_NORMAL
}

// 登录
type CmdWw321 struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw321) Reset()         { *m = CmdWw321{} }
func (m *CmdWw321) String() string { return proto.CompactTextString(m) }
func (*CmdWw321) ProtoMessage()    {}
func (*CmdWw321) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{3}
}
func (m *CmdWw321) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw321.Unmarshal(m, b)
}
func (m *CmdWw321) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw321.Marshal(b, m, deterministic)
}
func (dst *CmdWw321) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw321.Merge(dst, src)
}
func (m *CmdWw321) XXX_Size() int {
	return xxx_messageInfo_CmdWw321.Size(m)
}
func (m *CmdWw321) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw321.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw321 proto.InternalMessageInfo

func (m *CmdWw321) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 注销
type CmdWw322 struct {
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw322) Reset()         { *m = CmdWw322{} }
func (m *CmdWw322) String() string { return proto.CompactTextString(m) }
func (*CmdWw322) ProtoMessage()    {}
func (*CmdWw322) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{4}
}
func (m *CmdWw322) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw322.Unmarshal(m, b)
}
func (m *CmdWw322) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw322.Marshal(b, m, deterministic)
}
func (dst *CmdWw322) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw322.Merge(dst, src)
}
func (m *CmdWw322) XXX_Size() int {
	return xxx_messageInfo_CmdWw322.Size(m)
}
func (m *CmdWw322) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw322.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw322 proto.InternalMessageInfo

func (m *CmdWw322) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 上报用户信息
type CmdWw323 struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw323) Reset()         { *m = CmdWw323{} }
func (m *CmdWw323) String() string { return proto.CompactTextString(m) }
func (*CmdWw323) ProtoMessage()    {}
func (*CmdWw323) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{5}
}
func (m *CmdWw323) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw323.Unmarshal(m, b)
}
func (m *CmdWw323) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw323.Marshal(b, m, deterministic)
}
func (dst *CmdWw323) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw323.Merge(dst, src)
}
func (m *CmdWw323) XXX_Size() int {
	return xxx_messageInfo_CmdWw323.Size(m)
}
func (m *CmdWw323) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw323.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw323 proto.InternalMessageInfo

func (m *CmdWw323) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 修改头像
type CmdWw324 struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Data                 *User    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw324) Reset()         { *m = CmdWw324{} }
func (m *CmdWw324) String() string { return proto.CompactTextString(m) }
func (*CmdWw324) ProtoMessage()    {}
func (*CmdWw324) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{6}
}
func (m *CmdWw324) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw324.Unmarshal(m, b)
}
func (m *CmdWw324) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw324.Marshal(b, m, deterministic)
}
func (dst *CmdWw324) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw324.Merge(dst, src)
}
func (m *CmdWw324) XXX_Size() int {
	return xxx_messageInfo_CmdWw324.Size(m)
}
func (m *CmdWw324) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw324.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw324 proto.InternalMessageInfo

func (m *CmdWw324) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CmdWw324) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 获取登录账号二维码
type CmdWw325 struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw325) Reset()         { *m = CmdWw325{} }
func (m *CmdWw325) String() string { return proto.CompactTextString(m) }
func (*CmdWw325) ProtoMessage()    {}
func (*CmdWw325) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{7}
}
func (m *CmdWw325) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw325.Unmarshal(m, b)
}
func (m *CmdWw325) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw325.Marshal(b, m, deterministic)
}
func (dst *CmdWw325) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw325.Merge(dst, src)
}
func (m *CmdWw325) XXX_Size() int {
	return xxx_messageInfo_CmdWw325.Size(m)
}
func (m *CmdWw325) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw325.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw325 proto.InternalMessageInfo

func (m *CmdWw325) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 修改外部联系人备注
type CmdWw331 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Company              string   `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Phone                []string `protobuf:"bytes,4,rep,name=phone,proto3" json:"phone,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	RemarkUrl            string   `protobuf:"bytes,6,opt,name=remarkUrl,proto3" json:"remarkUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw331) Reset()         { *m = CmdWw331{} }
func (m *CmdWw331) String() string { return proto.CompactTextString(m) }
func (*CmdWw331) ProtoMessage()    {}
func (*CmdWw331) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{8}
}
func (m *CmdWw331) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw331.Unmarshal(m, b)
}
func (m *CmdWw331) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw331.Marshal(b, m, deterministic)
}
func (dst *CmdWw331) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw331.Merge(dst, src)
}
func (m *CmdWw331) XXX_Size() int {
	return xxx_messageInfo_CmdWw331.Size(m)
}
func (m *CmdWw331) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw331.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw331 proto.InternalMessageInfo

func (m *CmdWw331) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw331) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CmdWw331) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *CmdWw331) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *CmdWw331) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CmdWw331) GetRemarkUrl() string {
	if m != nil {
		return m.RemarkUrl
	}
	return ""
}

// 修改内部联系人备注
type CmdWw332 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw332) Reset()         { *m = CmdWw332{} }
func (m *CmdWw332) String() string { return proto.CompactTextString(m) }
func (*CmdWw332) ProtoMessage()    {}
func (*CmdWw332) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{9}
}
func (m *CmdWw332) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw332.Unmarshal(m, b)
}
func (m *CmdWw332) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw332.Marshal(b, m, deterministic)
}
func (dst *CmdWw332) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw332.Merge(dst, src)
}
func (m *CmdWw332) XXX_Size() int {
	return xxx_messageInfo_CmdWw332.Size(m)
}
func (m *CmdWw332) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw332.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw332 proto.InternalMessageInfo

func (m *CmdWw332) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw332) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CmdWw332) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

// 搜索联系人
type CmdWw333 struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Data                 []*User  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw333) Reset()         { *m = CmdWw333{} }
func (m *CmdWw333) String() string { return proto.CompactTextString(m) }
func (*CmdWw333) ProtoMessage()    {}
func (*CmdWw333) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{10}
}
func (m *CmdWw333) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw333.Unmarshal(m, b)
}
func (m *CmdWw333) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw333.Marshal(b, m, deterministic)
}
func (dst *CmdWw333) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw333.Merge(dst, src)
}
func (m *CmdWw333) XXX_Size() int {
	return xxx_messageInfo_CmdWw333.Size(m)
}
func (m *CmdWw333) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw333.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw333 proto.InternalMessageInfo

func (m *CmdWw333) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CmdWw333) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 添加联系人
type CmdWw334 struct {
	Id                   []int64  `protobuf:"varint,3,rep,packed,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw334) Reset()         { *m = CmdWw334{} }
func (m *CmdWw334) String() string { return proto.CompactTextString(m) }
func (*CmdWw334) ProtoMessage()    {}
func (*CmdWw334) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{11}
}
func (m *CmdWw334) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw334.Unmarshal(m, b)
}
func (m *CmdWw334) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw334.Marshal(b, m, deterministic)
}
func (dst *CmdWw334) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw334.Merge(dst, src)
}
func (m *CmdWw334) XXX_Size() int {
	return xxx_messageInfo_CmdWw334.Size(m)
}
func (m *CmdWw334) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw334.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw334 proto.InternalMessageInfo

func (m *CmdWw334) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

// 上报收到好友添加请求（仅用于客户端上报）
type CmdWw335 struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw335) Reset()         { *m = CmdWw335{} }
func (m *CmdWw335) String() string { return proto.CompactTextString(m) }
func (*CmdWw335) ProtoMessage()    {}
func (*CmdWw335) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{12}
}
func (m *CmdWw335) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw335.Unmarshal(m, b)
}
func (m *CmdWw335) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw335.Marshal(b, m, deterministic)
}
func (dst *CmdWw335) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw335.Merge(dst, src)
}
func (m *CmdWw335) XXX_Size() int {
	return xxx_messageInfo_CmdWw335.Size(m)
}
func (m *CmdWw335) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw335.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw335 proto.InternalMessageInfo

func (m *CmdWw335) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 同意/拒绝/查看收到的好友添加请求与CmdWw335配合使用
type CmdWw336 struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 CmdWw336_OperateType `protobuf:"varint,2,opt,name=type,proto3,enum=proto_pb.CmdWw336_OperateType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CmdWw336) Reset()         { *m = CmdWw336{} }
func (m *CmdWw336) String() string { return proto.CompactTextString(m) }
func (*CmdWw336) ProtoMessage()    {}
func (*CmdWw336) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{13}
}
func (m *CmdWw336) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw336.Unmarshal(m, b)
}
func (m *CmdWw336) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw336.Marshal(b, m, deterministic)
}
func (dst *CmdWw336) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw336.Merge(dst, src)
}
func (m *CmdWw336) XXX_Size() int {
	return xxx_messageInfo_CmdWw336.Size(m)
}
func (m *CmdWw336) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw336.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw336 proto.InternalMessageInfo

func (m *CmdWw336) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw336) GetType() CmdWw336_OperateType {
	if m != nil {
		return m.Type
	}
	return CmdWw336_AGREE
}

// 删除外部联系人
type CmdWw337 struct {
	Data                 []int64  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw337) Reset()         { *m = CmdWw337{} }
func (m *CmdWw337) String() string { return proto.CompactTextString(m) }
func (*CmdWw337) ProtoMessage()    {}
func (*CmdWw337) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{14}
}
func (m *CmdWw337) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw337.Unmarshal(m, b)
}
func (m *CmdWw337) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw337.Marshal(b, m, deterministic)
}
func (dst *CmdWw337) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw337.Merge(dst, src)
}
func (m *CmdWw337) XXX_Size() int {
	return xxx_messageInfo_CmdWw337.Size(m)
}
func (m *CmdWw337) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw337.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw337 proto.InternalMessageInfo

func (m *CmdWw337) GetData() []int64 {
	if m != nil {
		return m.Data
	}
	return nil
}

// 获取所有部门信息
type CmdWw338 struct {
	Data                 []*Department `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CmdWw338) Reset()         { *m = CmdWw338{} }
func (m *CmdWw338) String() string { return proto.CompactTextString(m) }
func (*CmdWw338) ProtoMessage()    {}
func (*CmdWw338) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{15}
}
func (m *CmdWw338) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw338.Unmarshal(m, b)
}
func (m *CmdWw338) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw338.Marshal(b, m, deterministic)
}
func (dst *CmdWw338) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw338.Merge(dst, src)
}
func (m *CmdWw338) XXX_Size() int {
	return xxx_messageInfo_CmdWw338.Size(m)
}
func (m *CmdWw338) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw338.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw338 proto.InternalMessageInfo

func (m *CmdWw338) GetData() []*Department {
	if m != nil {
		return m.Data
	}
	return nil
}

// 获取指定部门的用户信息
type CmdWw339 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []*User  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw339) Reset()         { *m = CmdWw339{} }
func (m *CmdWw339) String() string { return proto.CompactTextString(m) }
func (*CmdWw339) ProtoMessage()    {}
func (*CmdWw339) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{16}
}
func (m *CmdWw339) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw339.Unmarshal(m, b)
}
func (m *CmdWw339) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw339.Marshal(b, m, deterministic)
}
func (dst *CmdWw339) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw339.Merge(dst, src)
}
func (m *CmdWw339) XXX_Size() int {
	return xxx_messageInfo_CmdWw339.Size(m)
}
func (m *CmdWw339) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw339.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw339 proto.InternalMessageInfo

func (m *CmdWw339) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw339) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 获取企业下所有用户信息
type CmdWw3310 struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3310) Reset()         { *m = CmdWw3310{} }
func (m *CmdWw3310) String() string { return proto.CompactTextString(m) }
func (*CmdWw3310) ProtoMessage()    {}
func (*CmdWw3310) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{17}
}
func (m *CmdWw3310) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3310.Unmarshal(m, b)
}
func (m *CmdWw3310) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3310.Marshal(b, m, deterministic)
}
func (dst *CmdWw3310) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3310.Merge(dst, src)
}
func (m *CmdWw3310) XXX_Size() int {
	return xxx_messageInfo_CmdWw3310.Size(m)
}
func (m *CmdWw3310) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3310.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3310 proto.InternalMessageInfo

func (m *CmdWw3310) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 获取所有外部客户
type CmdWw3311 struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3311) Reset()         { *m = CmdWw3311{} }
func (m *CmdWw3311) String() string { return proto.CompactTextString(m) }
func (*CmdWw3311) ProtoMessage()    {}
func (*CmdWw3311) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{18}
}
func (m *CmdWw3311) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3311.Unmarshal(m, b)
}
func (m *CmdWw3311) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3311.Marshal(b, m, deterministic)
}
func (dst *CmdWw3311) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3311.Merge(dst, src)
}
func (m *CmdWw3311) XXX_Size() int {
	return xxx_messageInfo_CmdWw3311.Size(m)
}
func (m *CmdWw3311) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3311.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3311 proto.InternalMessageInfo

func (m *CmdWw3311) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 上报所有会话状态
type CmdWw341 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw341) Reset()         { *m = CmdWw341{} }
func (m *CmdWw341) String() string { return proto.CompactTextString(m) }
func (*CmdWw341) ProtoMessage()    {}
func (*CmdWw341) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{19}
}
func (m *CmdWw341) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw341.Unmarshal(m, b)
}
func (m *CmdWw341) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw341.Marshal(b, m, deterministic)
}
func (dst *CmdWw341) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw341.Merge(dst, src)
}
func (m *CmdWw341) XXX_Size() int {
	return xxx_messageInfo_CmdWw341.Size(m)
}
func (m *CmdWw341) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw341.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw341 proto.InternalMessageInfo

// 上报/获取所有会话列表
type CmdWw342 struct {
	Data                 []*Conversation `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CmdWw342) Reset()         { *m = CmdWw342{} }
func (m *CmdWw342) String() string { return proto.CompactTextString(m) }
func (*CmdWw342) ProtoMessage()    {}
func (*CmdWw342) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{20}
}
func (m *CmdWw342) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw342.Unmarshal(m, b)
}
func (m *CmdWw342) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw342.Marshal(b, m, deterministic)
}
func (dst *CmdWw342) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw342.Merge(dst, src)
}
func (m *CmdWw342) XXX_Size() int {
	return xxx_messageInfo_CmdWw342.Size(m)
}
func (m *CmdWw342) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw342.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw342 proto.InternalMessageInfo

func (m *CmdWw342) GetData() []*Conversation {
	if m != nil {
		return m.Data
	}
	return nil
}

// 上报/获取所有群会话列表
type CmdWw343 struct {
	Data                 []*Conversation `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CmdWw343) Reset()         { *m = CmdWw343{} }
func (m *CmdWw343) String() string { return proto.CompactTextString(m) }
func (*CmdWw343) ProtoMessage()    {}
func (*CmdWw343) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{21}
}
func (m *CmdWw343) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw343.Unmarshal(m, b)
}
func (m *CmdWw343) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw343.Marshal(b, m, deterministic)
}
func (dst *CmdWw343) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw343.Merge(dst, src)
}
func (m *CmdWw343) XXX_Size() int {
	return xxx_messageInfo_CmdWw343.Size(m)
}
func (m *CmdWw343) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw343.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw343 proto.InternalMessageInfo

func (m *CmdWw343) GetData() []*Conversation {
	if m != nil {
		return m.Data
	}
	return nil
}

// 上报/获取所有保存到通讯录的群会话列表
type CmdWw344 struct {
	Data                 []*Conversation `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CmdWw344) Reset()         { *m = CmdWw344{} }
func (m *CmdWw344) String() string { return proto.CompactTextString(m) }
func (*CmdWw344) ProtoMessage()    {}
func (*CmdWw344) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{22}
}
func (m *CmdWw344) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw344.Unmarshal(m, b)
}
func (m *CmdWw344) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw344.Marshal(b, m, deterministic)
}
func (dst *CmdWw344) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw344.Merge(dst, src)
}
func (m *CmdWw344) XXX_Size() int {
	return xxx_messageInfo_CmdWw344.Size(m)
}
func (m *CmdWw344) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw344.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw344 proto.InternalMessageInfo

func (m *CmdWw344) GetData() []*Conversation {
	if m != nil {
		return m.Data
	}
	return nil
}

// 创建群聊（勿要频繁调用，企业微信会根据企业主体下所有成员的活跃度限定每日建群的数量）
type CmdWw345 struct {
	Ids                  []int64       `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Data                 *Conversation `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CmdWw345) Reset()         { *m = CmdWw345{} }
func (m *CmdWw345) String() string { return proto.CompactTextString(m) }
func (*CmdWw345) ProtoMessage()    {}
func (*CmdWw345) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{23}
}
func (m *CmdWw345) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw345.Unmarshal(m, b)
}
func (m *CmdWw345) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw345.Marshal(b, m, deterministic)
}
func (dst *CmdWw345) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw345.Merge(dst, src)
}
func (m *CmdWw345) XXX_Size() int {
	return xxx_messageInfo_CmdWw345.Size(m)
}
func (m *CmdWw345) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw345.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw345 proto.InternalMessageInfo

func (m *CmdWw345) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *CmdWw345) GetData() *Conversation {
	if m != nil {
		return m.Data
	}
	return nil
}

// 退出群聊（勿频繁调用）
type CmdWw346 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw346) Reset()         { *m = CmdWw346{} }
func (m *CmdWw346) String() string { return proto.CompactTextString(m) }
func (*CmdWw346) ProtoMessage()    {}
func (*CmdWw346) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{24}
}
func (m *CmdWw346) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw346.Unmarshal(m, b)
}
func (m *CmdWw346) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw346.Marshal(b, m, deterministic)
}
func (dst *CmdWw346) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw346.Merge(dst, src)
}
func (m *CmdWw346) XXX_Size() int {
	return xxx_messageInfo_CmdWw346.Size(m)
}
func (m *CmdWw346) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw346.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw346 proto.InternalMessageInfo

func (m *CmdWw346) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 解散群聊（勿频繁调用）
type CmdWw347 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw347) Reset()         { *m = CmdWw347{} }
func (m *CmdWw347) String() string { return proto.CompactTextString(m) }
func (*CmdWw347) ProtoMessage()    {}
func (*CmdWw347) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{25}
}
func (m *CmdWw347) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw347.Unmarshal(m, b)
}
func (m *CmdWw347) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw347.Marshal(b, m, deterministic)
}
func (dst *CmdWw347) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw347.Merge(dst, src)
}
func (m *CmdWw347) XXX_Size() int {
	return xxx_messageInfo_CmdWw347.Size(m)
}
func (m *CmdWw347) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw347.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw347 proto.InternalMessageInfo

func (m *CmdWw347) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 修改群名称
type CmdWw348 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw348) Reset()         { *m = CmdWw348{} }
func (m *CmdWw348) String() string { return proto.CompactTextString(m) }
func (*CmdWw348) ProtoMessage()    {}
func (*CmdWw348) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{26}
}
func (m *CmdWw348) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw348.Unmarshal(m, b)
}
func (m *CmdWw348) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw348.Marshal(b, m, deterministic)
}
func (dst *CmdWw348) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw348.Merge(dst, src)
}
func (m *CmdWw348) XXX_Size() int {
	return xxx_messageInfo_CmdWw348.Size(m)
}
func (m *CmdWw348) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw348.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw348 proto.InternalMessageInfo

func (m *CmdWw348) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw348) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 修改登录账号群内昵称
type CmdWw349 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw349) Reset()         { *m = CmdWw349{} }
func (m *CmdWw349) String() string { return proto.CompactTextString(m) }
func (*CmdWw349) ProtoMessage()    {}
func (*CmdWw349) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{27}
}
func (m *CmdWw349) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw349.Unmarshal(m, b)
}
func (m *CmdWw349) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw349.Marshal(b, m, deterministic)
}
func (dst *CmdWw349) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw349.Merge(dst, src)
}
func (m *CmdWw349) XXX_Size() int {
	return xxx_messageInfo_CmdWw349.Size(m)
}
func (m *CmdWw349) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw349.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw349 proto.InternalMessageInfo

func (m *CmdWw349) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw349) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

// 获取群内成员信息
type CmdWw3410 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []*User  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3410) Reset()         { *m = CmdWw3410{} }
func (m *CmdWw3410) String() string { return proto.CompactTextString(m) }
func (*CmdWw3410) ProtoMessage()    {}
func (*CmdWw3410) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{28}
}
func (m *CmdWw3410) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3410.Unmarshal(m, b)
}
func (m *CmdWw3410) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3410.Marshal(b, m, deterministic)
}
func (dst *CmdWw3410) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3410.Merge(dst, src)
}
func (m *CmdWw3410) XXX_Size() int {
	return xxx_messageInfo_CmdWw3410.Size(m)
}
func (m *CmdWw3410) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3410.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3410 proto.InternalMessageInfo

func (m *CmdWw3410) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3410) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

// 邀请他人入群
type CmdWw3411 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  []int64  `protobuf:"varint,2,rep,packed,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3411) Reset()         { *m = CmdWw3411{} }
func (m *CmdWw3411) String() string { return proto.CompactTextString(m) }
func (*CmdWw3411) ProtoMessage()    {}
func (*CmdWw3411) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{29}
}
func (m *CmdWw3411) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3411.Unmarshal(m, b)
}
func (m *CmdWw3411) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3411.Marshal(b, m, deterministic)
}
func (dst *CmdWw3411) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3411.Merge(dst, src)
}
func (m *CmdWw3411) XXX_Size() int {
	return xxx_messageInfo_CmdWw3411.Size(m)
}
func (m *CmdWw3411) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3411.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3411 proto.InternalMessageInfo

func (m *CmdWw3411) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3411) GetUid() []int64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

// 添加他人入群
type CmdWw3412 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  []int64  `protobuf:"varint,2,rep,packed,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3412) Reset()         { *m = CmdWw3412{} }
func (m *CmdWw3412) String() string { return proto.CompactTextString(m) }
func (*CmdWw3412) ProtoMessage()    {}
func (*CmdWw3412) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{30}
}
func (m *CmdWw3412) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3412.Unmarshal(m, b)
}
func (m *CmdWw3412) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3412.Marshal(b, m, deterministic)
}
func (dst *CmdWw3412) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3412.Merge(dst, src)
}
func (m *CmdWw3412) XXX_Size() int {
	return xxx_messageInfo_CmdWw3412.Size(m)
}
func (m *CmdWw3412) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3412.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3412 proto.InternalMessageInfo

func (m *CmdWw3412) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3412) GetUid() []int64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

// 移除群聊
type CmdWw3413 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ids                  []int64  `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3413) Reset()         { *m = CmdWw3413{} }
func (m *CmdWw3413) String() string { return proto.CompactTextString(m) }
func (*CmdWw3413) ProtoMessage()    {}
func (*CmdWw3413) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{31}
}
func (m *CmdWw3413) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3413.Unmarshal(m, b)
}
func (m *CmdWw3413) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3413.Marshal(b, m, deterministic)
}
func (dst *CmdWw3413) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3413.Merge(dst, src)
}
func (m *CmdWw3413) XXX_Size() int {
	return xxx_messageInfo_CmdWw3413.Size(m)
}
func (m *CmdWw3413) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3413.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3413 proto.InternalMessageInfo

func (m *CmdWw3413) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3413) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

// 获取群二维码
type CmdWw3414 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3414) Reset()         { *m = CmdWw3414{} }
func (m *CmdWw3414) String() string { return proto.CompactTextString(m) }
func (*CmdWw3414) ProtoMessage()    {}
func (*CmdWw3414) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{32}
}
func (m *CmdWw3414) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3414.Unmarshal(m, b)
}
func (m *CmdWw3414) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3414.Marshal(b, m, deterministic)
}
func (dst *CmdWw3414) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3414.Merge(dst, src)
}
func (m *CmdWw3414) XXX_Size() int {
	return xxx_messageInfo_CmdWw3414.Size(m)
}
func (m *CmdWw3414) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3414.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3414 proto.InternalMessageInfo

func (m *CmdWw3414) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3414) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 设置群主
type CmdWw3415 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3415) Reset()         { *m = CmdWw3415{} }
func (m *CmdWw3415) String() string { return proto.CompactTextString(m) }
func (*CmdWw3415) ProtoMessage()    {}
func (*CmdWw3415) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{33}
}
func (m *CmdWw3415) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3415.Unmarshal(m, b)
}
func (m *CmdWw3415) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3415.Marshal(b, m, deterministic)
}
func (dst *CmdWw3415) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3415.Merge(dst, src)
}
func (m *CmdWw3415) XXX_Size() int {
	return xxx_messageInfo_CmdWw3415.Size(m)
}
func (m *CmdWw3415) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3415.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3415 proto.InternalMessageInfo

func (m *CmdWw3415) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3415) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// 设置群公告
type CmdWw3416 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Notice               string   `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3416) Reset()         { *m = CmdWw3416{} }
func (m *CmdWw3416) String() string { return proto.CompactTextString(m) }
func (*CmdWw3416) ProtoMessage()    {}
func (*CmdWw3416) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{34}
}
func (m *CmdWw3416) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3416.Unmarshal(m, b)
}
func (m *CmdWw3416) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3416.Marshal(b, m, deterministic)
}
func (dst *CmdWw3416) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3416.Merge(dst, src)
}
func (m *CmdWw3416) XXX_Size() int {
	return xxx_messageInfo_CmdWw3416.Size(m)
}
func (m *CmdWw3416) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3416.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3416 proto.InternalMessageInfo

func (m *CmdWw3416) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3416) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

// 将群保存或移除通讯录
type CmdWw3417 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Save                 bool     `protobuf:"varint,2,opt,name=save,proto3" json:"save,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3417) Reset()         { *m = CmdWw3417{} }
func (m *CmdWw3417) String() string { return proto.CompactTextString(m) }
func (*CmdWw3417) ProtoMessage()    {}
func (*CmdWw3417) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{35}
}
func (m *CmdWw3417) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3417.Unmarshal(m, b)
}
func (m *CmdWw3417) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3417.Marshal(b, m, deterministic)
}
func (dst *CmdWw3417) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3417.Merge(dst, src)
}
func (m *CmdWw3417) XXX_Size() int {
	return xxx_messageInfo_CmdWw3417.Size(m)
}
func (m *CmdWw3417) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3417.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3417 proto.InternalMessageInfo

func (m *CmdWw3417) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3417) GetSave() bool {
	if m != nil {
		return m.Save
	}
	return false
}

// 置顶/取消置顶
type CmdWw3418 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Top                  bool     `protobuf:"varint,2,opt,name=top,proto3" json:"top,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3418) Reset()         { *m = CmdWw3418{} }
func (m *CmdWw3418) String() string { return proto.CompactTextString(m) }
func (*CmdWw3418) ProtoMessage()    {}
func (*CmdWw3418) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{36}
}
func (m *CmdWw3418) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3418.Unmarshal(m, b)
}
func (m *CmdWw3418) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3418.Marshal(b, m, deterministic)
}
func (dst *CmdWw3418) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3418.Merge(dst, src)
}
func (m *CmdWw3418) XXX_Size() int {
	return xxx_messageInfo_CmdWw3418.Size(m)
}
func (m *CmdWw3418) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3418.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3418 proto.InternalMessageInfo

func (m *CmdWw3418) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3418) GetTop() bool {
	if m != nil {
		return m.Top
	}
	return false
}

// 设置/取消免打扰
type CmdWw3419 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Shield               bool     `protobuf:"varint,2,opt,name=shield,proto3" json:"shield,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3419) Reset()         { *m = CmdWw3419{} }
func (m *CmdWw3419) String() string { return proto.CompactTextString(m) }
func (*CmdWw3419) ProtoMessage()    {}
func (*CmdWw3419) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{37}
}
func (m *CmdWw3419) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3419.Unmarshal(m, b)
}
func (m *CmdWw3419) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3419.Marshal(b, m, deterministic)
}
func (dst *CmdWw3419) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3419.Merge(dst, src)
}
func (m *CmdWw3419) XXX_Size() int {
	return xxx_messageInfo_CmdWw3419.Size(m)
}
func (m *CmdWw3419) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3419.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3419 proto.InternalMessageInfo

func (m *CmdWw3419) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3419) GetShield() bool {
	if m != nil {
		return m.Shield
	}
	return false
}

// 设置/取消禁言
type CmdWw3420 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Forbidden            bool     `protobuf:"varint,2,opt,name=forbidden,proto3" json:"forbidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3420) Reset()         { *m = CmdWw3420{} }
func (m *CmdWw3420) String() string { return proto.CompactTextString(m) }
func (*CmdWw3420) ProtoMessage()    {}
func (*CmdWw3420) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{38}
}
func (m *CmdWw3420) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3420.Unmarshal(m, b)
}
func (m *CmdWw3420) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3420.Marshal(b, m, deterministic)
}
func (dst *CmdWw3420) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3420.Merge(dst, src)
}
func (m *CmdWw3420) XXX_Size() int {
	return xxx_messageInfo_CmdWw3420.Size(m)
}
func (m *CmdWw3420) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3420.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3420 proto.InternalMessageInfo

func (m *CmdWw3420) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3420) GetForbidden() bool {
	if m != nil {
		return m.Forbidden
	}
	return false
}

// 设置/取消入群确认
type CmdWw3421 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Confirm              bool     `protobuf:"varint,2,opt,name=confirm,proto3" json:"confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw3421) Reset()         { *m = CmdWw3421{} }
func (m *CmdWw3421) String() string { return proto.CompactTextString(m) }
func (*CmdWw3421) ProtoMessage()    {}
func (*CmdWw3421) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{39}
}
func (m *CmdWw3421) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw3421.Unmarshal(m, b)
}
func (m *CmdWw3421) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw3421.Marshal(b, m, deterministic)
}
func (dst *CmdWw3421) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw3421.Merge(dst, src)
}
func (m *CmdWw3421) XXX_Size() int {
	return xxx_messageInfo_CmdWw3421.Size(m)
}
func (m *CmdWw3421) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw3421.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw3421 proto.InternalMessageInfo

func (m *CmdWw3421) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw3421) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

// 同步上报消息
type CmdWw351 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw351) Reset()         { *m = CmdWw351{} }
func (m *CmdWw351) String() string { return proto.CompactTextString(m) }
func (*CmdWw351) ProtoMessage()    {}
func (*CmdWw351) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{40}
}
func (m *CmdWw351) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw351.Unmarshal(m, b)
}
func (m *CmdWw351) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw351.Marshal(b, m, deterministic)
}
func (dst *CmdWw351) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw351.Merge(dst, src)
}
func (m *CmdWw351) XXX_Size() int {
	return xxx_messageInfo_CmdWw351.Size(m)
}
func (m *CmdWw351) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw351.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw351 proto.InternalMessageInfo

// 发送文本消息
type CmdWw352 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Uid                  []int64  `protobuf:"varint,3,rep,packed,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw352) Reset()         { *m = CmdWw352{} }
func (m *CmdWw352) String() string { return proto.CompactTextString(m) }
func (*CmdWw352) ProtoMessage()    {}
func (*CmdWw352) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{41}
}
func (m *CmdWw352) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw352.Unmarshal(m, b)
}
func (m *CmdWw352) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw352.Marshal(b, m, deterministic)
}
func (dst *CmdWw352) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw352.Merge(dst, src)
}
func (m *CmdWw352) XXX_Size() int {
	return xxx_messageInfo_CmdWw352.Size(m)
}
func (m *CmdWw352) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw352.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw352 proto.InternalMessageInfo

func (m *CmdWw352) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw352) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CmdWw352) GetUid() []int64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

// 发送图片消息
type CmdWw353 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw353) Reset()         { *m = CmdWw353{} }
func (m *CmdWw353) String() string { return proto.CompactTextString(m) }
func (*CmdWw353) ProtoMessage()    {}
func (*CmdWw353) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{42}
}
func (m *CmdWw353) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw353.Unmarshal(m, b)
}
func (m *CmdWw353) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw353.Marshal(b, m, deterministic)
}
func (dst *CmdWw353) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw353.Merge(dst, src)
}
func (m *CmdWw353) XXX_Size() int {
	return xxx_messageInfo_CmdWw353.Size(m)
}
func (m *CmdWw353) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw353.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw353 proto.InternalMessageInfo

func (m *CmdWw353) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw353) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 发送语音消息（超过60的语音不发送）
type CmdWw354 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Time                 int32    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw354) Reset()         { *m = CmdWw354{} }
func (m *CmdWw354) String() string { return proto.CompactTextString(m) }
func (*CmdWw354) ProtoMessage()    {}
func (*CmdWw354) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{43}
}
func (m *CmdWw354) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw354.Unmarshal(m, b)
}
func (m *CmdWw354) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw354.Marshal(b, m, deterministic)
}
func (dst *CmdWw354) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw354.Merge(dst, src)
}
func (m *CmdWw354) XXX_Size() int {
	return xxx_messageInfo_CmdWw354.Size(m)
}
func (m *CmdWw354) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw354.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw354 proto.InternalMessageInfo

func (m *CmdWw354) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw354) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CmdWw354) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 发送视频消息
type CmdWw355 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	PreviewUrl           string   `protobuf:"bytes,3,opt,name=previewUrl,proto3" json:"previewUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw355) Reset()         { *m = CmdWw355{} }
func (m *CmdWw355) String() string { return proto.CompactTextString(m) }
func (*CmdWw355) ProtoMessage()    {}
func (*CmdWw355) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{44}
}
func (m *CmdWw355) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw355.Unmarshal(m, b)
}
func (m *CmdWw355) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw355.Marshal(b, m, deterministic)
}
func (dst *CmdWw355) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw355.Merge(dst, src)
}
func (m *CmdWw355) XXX_Size() int {
	return xxx_messageInfo_CmdWw355.Size(m)
}
func (m *CmdWw355) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw355.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw355 proto.InternalMessageInfo

func (m *CmdWw355) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw355) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CmdWw355) GetPreviewUrl() string {
	if m != nil {
		return m.PreviewUrl
	}
	return ""
}

// 发送文件消息（文件大小超过100M不发送）
type CmdWw356 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw356) Reset()         { *m = CmdWw356{} }
func (m *CmdWw356) String() string { return proto.CompactTextString(m) }
func (*CmdWw356) ProtoMessage()    {}
func (*CmdWw356) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{45}
}
func (m *CmdWw356) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw356.Unmarshal(m, b)
}
func (m *CmdWw356) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw356.Marshal(b, m, deterministic)
}
func (dst *CmdWw356) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw356.Merge(dst, src)
}
func (m *CmdWw356) XXX_Size() int {
	return xxx_messageInfo_CmdWw356.Size(m)
}
func (m *CmdWw356) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw356.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw356 proto.InternalMessageInfo

func (m *CmdWw356) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw356) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 发送链接消息
type CmdWw357 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkUrl              string   `protobuf:"bytes,2,opt,name=linkUrl,proto3" json:"linkUrl,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw357) Reset()         { *m = CmdWw357{} }
func (m *CmdWw357) String() string { return proto.CompactTextString(m) }
func (*CmdWw357) ProtoMessage()    {}
func (*CmdWw357) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{46}
}
func (m *CmdWw357) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw357.Unmarshal(m, b)
}
func (m *CmdWw357) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw357.Marshal(b, m, deterministic)
}
func (dst *CmdWw357) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw357.Merge(dst, src)
}
func (m *CmdWw357) XXX_Size() int {
	return xxx_messageInfo_CmdWw357.Size(m)
}
func (m *CmdWw357) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw357.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw357 proto.InternalMessageInfo

func (m *CmdWw357) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw357) GetLinkUrl() string {
	if m != nil {
		return m.LinkUrl
	}
	return ""
}

func (m *CmdWw357) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CmdWw357) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CmdWw357) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

// 发送地理位置消息
type CmdWw358 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Zoom                 float64  `protobuf:"fixed64,6,opt,name=zoom,proto3" json:"zoom,omitempty"`
	StaticMapUrl         string   `protobuf:"bytes,7,opt,name=staticMapUrl,proto3" json:"staticMapUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw358) Reset()         { *m = CmdWw358{} }
func (m *CmdWw358) String() string { return proto.CompactTextString(m) }
func (*CmdWw358) ProtoMessage()    {}
func (*CmdWw358) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{47}
}
func (m *CmdWw358) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw358.Unmarshal(m, b)
}
func (m *CmdWw358) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw358.Marshal(b, m, deterministic)
}
func (dst *CmdWw358) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw358.Merge(dst, src)
}
func (m *CmdWw358) XXX_Size() int {
	return xxx_messageInfo_CmdWw358.Size(m)
}
func (m *CmdWw358) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw358.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw358 proto.InternalMessageInfo

func (m *CmdWw358) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw358) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *CmdWw358) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *CmdWw358) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CmdWw358) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CmdWw358) GetZoom() float64 {
	if m != nil {
		return m.Zoom
	}
	return 0
}

func (m *CmdWw358) GetStaticMapUrl() string {
	if m != nil {
		return m.StaticMapUrl
	}
	return ""
}

// 发送小程序消息
type CmdWw359 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Appid                string   `protobuf:"bytes,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Pagepath             string   `protobuf:"bytes,6,opt,name=pagepath,proto3" json:"pagepath,omitempty"`
	Version              int32    `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Type                 int32    `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	ThumbUrl             string   `protobuf:"bytes,9,opt,name=thumbUrl,proto3" json:"thumbUrl,omitempty"`
	WeappIconUrl         string   `protobuf:"bytes,10,opt,name=weappIconUrl,proto3" json:"weappIconUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdWw359) Reset()         { *m = CmdWw359{} }
func (m *CmdWw359) String() string { return proto.CompactTextString(m) }
func (*CmdWw359) ProtoMessage()    {}
func (*CmdWw359) Descriptor() ([]byte, []int) {
	return fileDescriptor_WwCmd_4b2250890ff2b43d, []int{48}
}
func (m *CmdWw359) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdWw359.Unmarshal(m, b)
}
func (m *CmdWw359) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdWw359.Marshal(b, m, deterministic)
}
func (dst *CmdWw359) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdWw359.Merge(dst, src)
}
func (m *CmdWw359) XXX_Size() int {
	return xxx_messageInfo_CmdWw359.Size(m)
}
func (m *CmdWw359) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdWw359.DiscardUnknown(m)
}

var xxx_messageInfo_CmdWw359 proto.InternalMessageInfo

func (m *CmdWw359) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CmdWw359) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *CmdWw359) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CmdWw359) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CmdWw359) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CmdWw359) GetPagepath() string {
	if m != nil {
		return m.Pagepath
	}
	return ""
}

func (m *CmdWw359) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CmdWw359) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CmdWw359) GetThumbUrl() string {
	if m != nil {
		return m.ThumbUrl
	}
	return ""
}

func (m *CmdWw359) GetWeappIconUrl() string {
	if m != nil {
		return m.WeappIconUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "proto_pb.User")
	proto.RegisterType((*Department)(nil), "proto_pb.Department")
	proto.RegisterType((*Conversation)(nil), "proto_pb.Conversation")
	proto.RegisterType((*CmdWw321)(nil), "proto_pb.CmdWw321")
	proto.RegisterType((*CmdWw322)(nil), "proto_pb.CmdWw322")
	proto.RegisterType((*CmdWw323)(nil), "proto_pb.CmdWw323")
	proto.RegisterType((*CmdWw324)(nil), "proto_pb.CmdWw324")
	proto.RegisterType((*CmdWw325)(nil), "proto_pb.CmdWw325")
	proto.RegisterType((*CmdWw331)(nil), "proto_pb.CmdWw331")
	proto.RegisterType((*CmdWw332)(nil), "proto_pb.CmdWw332")
	proto.RegisterType((*CmdWw333)(nil), "proto_pb.CmdWw333")
	proto.RegisterType((*CmdWw334)(nil), "proto_pb.CmdWw334")
	proto.RegisterType((*CmdWw335)(nil), "proto_pb.CmdWw335")
	proto.RegisterType((*CmdWw336)(nil), "proto_pb.CmdWw336")
	proto.RegisterType((*CmdWw337)(nil), "proto_pb.CmdWw337")
	proto.RegisterType((*CmdWw338)(nil), "proto_pb.CmdWw338")
	proto.RegisterType((*CmdWw339)(nil), "proto_pb.CmdWw339")
	proto.RegisterType((*CmdWw3310)(nil), "proto_pb.CmdWw3310")
	proto.RegisterType((*CmdWw3311)(nil), "proto_pb.CmdWw3311")
	proto.RegisterType((*CmdWw341)(nil), "proto_pb.CmdWw341")
	proto.RegisterType((*CmdWw342)(nil), "proto_pb.CmdWw342")
	proto.RegisterType((*CmdWw343)(nil), "proto_pb.CmdWw343")
	proto.RegisterType((*CmdWw344)(nil), "proto_pb.CmdWw344")
	proto.RegisterType((*CmdWw345)(nil), "proto_pb.CmdWw345")
	proto.RegisterType((*CmdWw346)(nil), "proto_pb.CmdWw346")
	proto.RegisterType((*CmdWw347)(nil), "proto_pb.CmdWw347")
	proto.RegisterType((*CmdWw348)(nil), "proto_pb.CmdWw348")
	proto.RegisterType((*CmdWw349)(nil), "proto_pb.CmdWw349")
	proto.RegisterType((*CmdWw3410)(nil), "proto_pb.CmdWw3410")
	proto.RegisterType((*CmdWw3411)(nil), "proto_pb.CmdWw3411")
	proto.RegisterType((*CmdWw3412)(nil), "proto_pb.CmdWw3412")
	proto.RegisterType((*CmdWw3413)(nil), "proto_pb.CmdWw3413")
	proto.RegisterType((*CmdWw3414)(nil), "proto_pb.CmdWw3414")
	proto.RegisterType((*CmdWw3415)(nil), "proto_pb.CmdWw3415")
	proto.RegisterType((*CmdWw3416)(nil), "proto_pb.CmdWw3416")
	proto.RegisterType((*CmdWw3417)(nil), "proto_pb.CmdWw3417")
	proto.RegisterType((*CmdWw3418)(nil), "proto_pb.CmdWw3418")
	proto.RegisterType((*CmdWw3419)(nil), "proto_pb.CmdWw3419")
	proto.RegisterType((*CmdWw3420)(nil), "proto_pb.CmdWw3420")
	proto.RegisterType((*CmdWw3421)(nil), "proto_pb.CmdWw3421")
	proto.RegisterType((*CmdWw351)(nil), "proto_pb.CmdWw351")
	proto.RegisterType((*CmdWw352)(nil), "proto_pb.CmdWw352")
	proto.RegisterType((*CmdWw353)(nil), "proto_pb.CmdWw353")
	proto.RegisterType((*CmdWw354)(nil), "proto_pb.CmdWw354")
	proto.RegisterType((*CmdWw355)(nil), "proto_pb.CmdWw355")
	proto.RegisterType((*CmdWw356)(nil), "proto_pb.CmdWw356")
	proto.RegisterType((*CmdWw357)(nil), "proto_pb.CmdWw357")
	proto.RegisterType((*CmdWw358)(nil), "proto_pb.CmdWw358")
	proto.RegisterType((*CmdWw359)(nil), "proto_pb.CmdWw359")
	proto.RegisterEnum("proto_pb.Conversation_ConvType", Conversation_ConvType_name, Conversation_ConvType_value)
	proto.RegisterEnum("proto_pb.Conversation_RoomType", Conversation_RoomType_name, Conversation_RoomType_value)
	proto.RegisterEnum("proto_pb.CmdWw336_OperateType", CmdWw336_OperateType_name, CmdWw336_OperateType_value)
}

func init() { proto.RegisterFile("WwCmd.proto", fileDescriptor_WwCmd_4b2250890ff2b43d) }

var fileDescriptor_WwCmd_4b2250890ff2b43d = []byte{
	// 1370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x5b, 0x6e, 0xdb, 0xc6,
	0x1a, 0x8e, 0x48, 0x49, 0xa6, 0xc6, 0x3e, 0x3e, 0x02, 0x11, 0x04, 0x84, 0x11, 0xf8, 0x18, 0xc4,
	0x79, 0x08, 0x8a, 0x54, 0x89, 0x6e, 0xb6, 0x83, 0x02, 0x6d, 0x1d, 0x47, 0x49, 0x8c, 0x28, 0x52,
	0x40, 0xcb, 0x48, 0xdf, 0x8a, 0x91, 0x38, 0xb1, 0xa7, 0x16, 0x39, 0x04, 0x39, 0xb6, 0xe3, 0x3c,
	0x14, 0x5d, 0x44, 0xd7, 0xd1, 0x15, 0x74, 0x3b, 0xdd, 0x41, 0x17, 0x50, 0xfc, 0x33, 0xc3, 0x99,
	0x51, 0xa4, 0xa4, 0x4a, 0x9e, 0xf8, 0xdf, 0xf9, 0xfd, 0x97, 0xb9, 0xa1, 0xcd, 0xb7, 0x37, 0xc7,
	0x49, 0xdc, 0xca, 0x72, 0xc6, 0x99, 0xef, 0x89, 0xcf, 0xcf, 0xd9, 0x34, 0xfc, 0xdb, 0x41, 0xd5,
	0xb3, 0x82, 0xe4, 0xfe, 0x36, 0x72, 0x68, 0x1c, 0x54, 0xf6, 0x2a, 0x0f, 0xdc, 0xc8, 0xa1, 0xb1,
	0xef, 0xa3, 0x6a, 0x8a, 0x13, 0x12, 0x38, 0x7b, 0x95, 0x07, 0x8d, 0x48, 0xd0, 0xfe, 0x0e, 0xf2,
	0x52, 0x3a, 0xbb, 0x14, 0x72, 0x57, 0xc8, 0x35, 0xef, 0xdf, 0x45, 0x35, 0x3c, 0xa7, 0xb8, 0x08,
	0xaa, 0x42, 0x21, 0x19, 0xff, 0x3e, 0x6a, 0xe0, 0x6b, 0xcc, 0x71, 0x7e, 0x96, 0xcf, 0x83, 0x9a,
	0xd0, 0x18, 0x81, 0x7f, 0x0f, 0xd5, 0xcf, 0x49, 0x1a, 0x93, 0x3c, 0xa8, 0x8b, 0xff, 0x2a, 0x0e,
	0x62, 0x65, 0x17, 0x2c, 0x25, 0xc1, 0x86, 0x8c, 0x25, 0x18, 0xb0, 0x4e, 0xd8, 0x94, 0xce, 0x49,
	0xe0, 0x09, 0xb1, 0xe2, 0x40, 0x8e, 0x67, 0x33, 0x4e, 0xe3, 0xa0, 0x21, 0xe5, 0x92, 0x03, 0xf9,
	0x8c, 0xe5, 0xd9, 0x49, 0x1c, 0x20, 0x19, 0x5d, 0x72, 0x90, 0x05, 0x50, 0x23, 0xc8, 0x62, 0x53,
	0x66, 0x51, 0xf2, 0x80, 0x17, 0xe8, 0xe7, 0x42, 0xb9, 0x25, 0xf1, 0x6a, 0x81, 0xbf, 0x87, 0x36,
	0x81, 0x39, 0x8a, 0xe3, 0x9c, 0x14, 0x45, 0xf0, 0x1f, 0xa1, 0xb7, 0x45, 0x7e, 0x13, 0xb9, 0xbf,
	0xb0, 0x69, 0xb0, 0x2d, 0x34, 0x40, 0x8a, 0xba, 0x64, 0xd9, 0xfc, 0x36, 0xf8, 0xaf, 0xaa, 0x0b,
	0x30, 0xe1, 0x1f, 0x15, 0x84, 0x9e, 0x91, 0x0c, 0xe7, 0x3c, 0x21, 0x29, 0x5f, 0xab, 0xf8, 0x01,
	0xda, 0x00, 0xfb, 0xdb, 0x93, 0x58, 0xd4, 0xbe, 0x16, 0x95, 0x2c, 0x24, 0x7a, 0x81, 0x8b, 0x53,
	0x96, 0x8a, 0xda, 0x7b, 0x91, 0xe2, 0xe0, 0xd7, 0x73, 0x72, 0x4d, 0x64, 0xe1, 0x6b, 0x91, 0x64,
	0x20, 0xc5, 0xab, 0x82, 0xe4, 0xc7, 0xec, 0x2a, 0xe5, 0xa2, 0xee, 0xb5, 0xc8, 0x08, 0xac, 0xa2,
	0x6d, 0xd8, 0x45, 0x0b, 0xff, 0x72, 0xd1, 0xd6, 0x31, 0x4b, 0xaf, 0x49, 0x5e, 0x60, 0x4e, 0x59,
	0xba, 0x16, 0xe4, 0x85, 0xee, 0xbb, 0x1f, 0x77, 0x1f, 0x6a, 0x9d, 0x13, 0xcc, 0x59, 0x7e, 0x12,
	0x0b, 0xe4, 0x6e, 0x64, 0x04, 0x00, 0x84, 0xbc, 0xa7, 0x9c, 0xc4, 0x02, 0xbd, 0x17, 0x29, 0x0e,
	0x7a, 0x90, 0x90, 0x64, 0xba, 0x98, 0x80, 0x2d, 0xf2, 0x77, 0x11, 0x12, 0x61, 0xc8, 0x84, 0x26,
	0x44, 0xa5, 0x61, 0x49, 0x40, 0x9f, 0xb0, 0x98, 0xbe, 0xbb, 0x15, 0x7a, 0x4f, 0xea, 0x8d, 0xc4,
	0xff, 0x0e, 0xe6, 0x23, 0xbd, 0x9e, 0xdc, 0x66, 0x44, 0x4c, 0xd4, 0x76, 0xe7, 0x7f, 0xad, 0x72,
	0xbd, 0xb4, 0xec, 0x1a, 0x08, 0x06, 0xcc, 0x22, 0xed, 0x00, 0xce, 0x39, 0x63, 0x89, 0x70, 0x46,
	0x9f, 0x75, 0x8e, 0x94, 0x59, 0xa4, 0x1d, 0xc2, 0x87, 0xc8, 0x2b, 0x43, 0xfa, 0x08, 0xd5, 0x4f,
	0x4f, 0x46, 0x2f, 0x86, 0x83, 0xe6, 0x1d, 0xbf, 0x81, 0x6a, 0x2f, 0xa2, 0xf1, 0xd9, 0x9b, 0x66,
	0x05, 0xc8, 0xf1, 0xe4, 0xe5, 0x20, 0x6a, 0x3a, 0xe1, 0x29, 0xf2, 0xca, 0x18, 0x60, 0x3d, 0x1a,
	0x47, 0xaf, 0x8f, 0x86, 0xcd, 0x3b, 0xfe, 0x06, 0x72, 0x8f, 0x86, 0xc3, 0x66, 0xc5, 0xdf, 0x42,
	0xde, 0xe0, 0xa7, 0xc9, 0x20, 0x1a, 0x1d, 0x0d, 0x9b, 0x8e, 0xbf, 0x8d, 0xd0, 0xb3, 0xc1, 0x9b,
	0xa3, 0x68, 0xf2, 0x7a, 0x30, 0x9a, 0x34, 0x5d, 0x7f, 0x13, 0x6d, 0x9c, 0x8d, 0x5e, 0x8d, 0xc6,
	0x6f, 0x47, 0xcd, 0x2a, 0xf8, 0x3c, 0x1d, 0x4f, 0x9a, 0xb5, 0x70, 0x17, 0x79, 0xc7, 0x49, 0xfc,
	0xf6, 0xa6, 0xdb, 0x69, 0x43, 0x4b, 0x63, 0xcc, 0xb1, 0x68, 0x72, 0x23, 0x12, 0xb4, 0xa5, 0xef,
	0x68, 0xbd, 0x6b, 0xe9, 0x5b, 0x5a, 0xdf, 0xf5, 0x43, 0xcb, 0x7f, 0xb3, 0xb3, 0x6d, 0xea, 0x00,
	0x1b, 0x8e, 0xb2, 0xff, 0x51, 0xdb, 0xf7, 0x60, 0xf1, 0x5c, 0xe5, 0x73, 0xf5, 0x3b, 0x20, 0x75,
	0x04, 0xe7, 0x33, 0x11, 0x0c, 0xa2, 0xfe, 0x02, 0xe2, 0x2d, 0xa5, 0xff, 0xbd, 0x52, 0x1a, 0x74,
	0xdb, 0x4b, 0x53, 0x7b, 0x0f, 0xd5, 0x73, 0x92, 0xe0, 0xfc, 0x52, 0xcd, 0xad, 0xe2, 0x60, 0xb1,
	0xcd, 0x58, 0x92, 0xe1, 0xf4, 0x56, 0x65, 0x57, 0xb2, 0x66, 0x6f, 0xaa, 0xee, 0xb9, 0x66, 0x6f,
	0x82, 0x1f, 0x93, 0x62, 0xa6, 0xb6, 0x38, 0x41, 0xc3, 0x7c, 0xcb, 0x68, 0x30, 0xfd, 0x75, 0x39,
	0xfd, 0x5a, 0x10, 0x3e, 0xd7, 0xa8, 0x3a, 0x6b, 0xa3, 0x2a, 0xff, 0xe2, 0x9a, 0xbf, 0x84, 0xcf,
	0x74, 0x9c, 0xae, 0xc1, 0x56, 0xb1, 0xf7, 0x4d, 0x53, 0x44, 0xf7, 0x93, 0x45, 0xdc, 0xd1, 0x51,
	0x7a, 0x0a, 0x8d, 0xbb, 0xe7, 0x4a, 0x34, 0xa6, 0xa5, 0xdd, 0xbe, 0xd5, 0xd2, 0x4f, 0xc7, 0xfa,
	0x55, 0xdb, 0xef, 0x2f, 0x65, 0xd6, 0x41, 0x55, 0x0e, 0x4b, 0xc3, 0x11, 0x4b, 0x63, 0xd7, 0x5a,
	0x1a, 0xca, 0xa3, 0x35, 0xce, 0x48, 0x0e, 0x2b, 0x15, 0x56, 0x86, 0xb0, 0x0d, 0x5b, 0x68, 0xd3,
	0x12, 0xc2, 0x0a, 0x38, 0x7a, 0x11, 0x0d, 0x60, 0x5d, 0x20, 0x54, 0x8f, 0x06, 0xcf, 0xcf, 0x4e,
	0x07, 0xcd, 0x8a, 0xef, 0xa1, 0xea, 0x70, 0x3c, 0x7e, 0xd5, 0x74, 0xcc, 0x40, 0x74, 0x0f, 0xac,
	0x81, 0x80, 0x6c, 0x24, 0xbe, 0x9e, 0xd6, 0x1f, 0xfa, 0x0f, 0x16, 0xf2, 0xb9, 0x6b, 0xf0, 0x98,
	0xcd, 0x59, 0x79, 0x7d, 0xaf, 0xbd, 0x9e, 0x2c, 0x65, 0xb5, 0x4e, 0x85, 0x1f, 0xa1, 0x46, 0x39,
	0x85, 0x8f, 0xd7, 0x2a, 0xa3, 0xe5, 0xd0, 0x5e, 0xcb, 0x01, 0x95, 0x08, 0x7b, 0xed, 0x70, 0x5f,
	0xd3, 0x1d, 0xff, 0x9b, 0x05, 0xdf, 0x7b, 0xab, 0xb7, 0x23, 0x15, 0xc3, 0xf8, 0x75, 0xbf, 0xd2,
	0xaf, 0xf7, 0x45, 0x7e, 0x2f, 0xb5, 0x5f, 0x1f, 0x96, 0x3f, 0x8d, 0x0b, 0xd5, 0x2a, 0x20, 0x75,
	0x24, 0xb9, 0xfc, 0x3f, 0x1f, 0x49, 0x4f, 0x70, 0x6f, 0x69, 0xea, 0x2c, 0xdd, 0xc1, 0x92, 0x4e,
	0x4f, 0x77, 0xef, 0x70, 0x9d, 0x33, 0xcd, 0xca, 0x74, 0x79, 0x0e, 0xec, 0xfb, 0x91, 0xb3, 0x78,
	0x3f, 0x0a, 0x7f, 0x28, 0xdb, 0xd9, 0x6b, 0x3f, 0xfe, 0xaa, 0x01, 0xfa, 0xd6, 0x04, 0x58, 0xde,
	0xc7, 0x60, 0xeb, 0xa4, 0xb1, 0xf0, 0x77, 0x23, 0x20, 0x6d, 0xf3, 0xce, 0x97, 0x99, 0x77, 0x57,
	0x99, 0x43, 0x67, 0x1c, 0xdd, 0x19, 0x33, 0x9c, 0xbd, 0x76, 0x6f, 0x55, 0xd9, 0x74, 0xdb, 0xb6,
	0x96, 0xd1, 0xf7, 0x3f, 0x0d, 0xa7, 0x52, 0xc2, 0xe9, 0x1a, 0xf3, 0xfd, 0x55, 0xdb, 0x63, 0xca,
	0x38, 0x9d, 0x95, 0x45, 0x56, 0x9c, 0x0d, 0xea, 0x60, 0x15, 0xa8, 0x02, 0x5f, 0x4b, 0x17, 0x2f,
	0x12, 0xb4, 0x0d, 0xea, 0x70, 0x15, 0x28, 0xce, 0x32, 0x65, 0x0f, 0xa4, 0x0d, 0xea, 0xc9, 0x2a,
	0x50, 0xc5, 0x05, 0x25, 0xf3, 0x58, 0x79, 0x28, 0x2e, 0x7c, 0xa2, 0x9d, 0x3a, 0xcb, 0x7d, 0xbf,
	0x8f, 0x1a, 0xef, 0x58, 0x3e, 0xa5, 0x71, 0x4c, 0x52, 0xe5, 0x67, 0x04, 0x61, 0xdf, 0xb8, 0x2e,
	0x77, 0x5c, 0x9c, 0x50, 0xe9, 0x3b, 0x9a, 0x27, 0xca, 0xb1, 0x64, 0xcd, 0x3e, 0xd0, 0x6f, 0x9b,
	0xe3, 0xb5, 0xdf, 0x59, 0x55, 0x11, 0x4e, 0xde, 0xf3, 0x72, 0xba, 0x81, 0x2e, 0x3b, 0xe1, 0x9a,
	0xc1, 0x78, 0xa8, 0x23, 0xac, 0x9c, 0x0b, 0x38, 0xb0, 0x1d, 0x7d, 0x60, 0x5b, 0xff, 0xeb, 0xfd,
	0xbb, 0xb5, 0x40, 0x40, 0xd5, 0x5b, 0xa2, 0x16, 0x09, 0x3a, 0x1c, 0xea, 0x08, 0xfd, 0x35, 0x22,
	0xec, 0x22, 0x94, 0xe5, 0xe4, 0x9a, 0x92, 0x1b, 0x73, 0xc5, 0xb4, 0x24, 0x16, 0xfa, 0xfd, 0x35,
	0xd0, 0x7f, 0xd0, 0xd6, 0x07, 0xab, 0xea, 0x3d, 0xa7, 0xa9, 0x38, 0xcb, 0xa5, 0x47, 0xc9, 0xc2,
	0xa9, 0xcb, 0x29, 0x9f, 0x97, 0x4f, 0x22, 0xc9, 0xe8, 0xb3, 0xba, 0x6a, 0xdd, 0x08, 0x76, 0x90,
	0x47, 0x13, 0x7c, 0x4e, 0xcc, 0x63, 0x48, 0xf3, 0xe1, 0x9f, 0xfa, 0x9a, 0xd2, 0x3f, 0x5c, 0xb5,
	0xb1, 0xcc, 0x31, 0xa7, 0xfc, 0x2a, 0x96, 0x03, 0x5c, 0x89, 0x34, 0x0f, 0x33, 0x34, 0x67, 0xe9,
	0xb9, 0x54, 0xba, 0x42, 0x69, 0x04, 0x00, 0x1b, 0xab, 0xe7, 0x8a, 0x44, 0x52, 0xb2, 0x06, 0x76,
	0xed, 0x23, 0xd8, 0x1f, 0x18, 0x4b, 0xc4, 0x7d, 0xa5, 0x12, 0x09, 0xda, 0x0f, 0xd1, 0x56, 0xc1,
	0x31, 0xa7, 0xb3, 0xd7, 0x38, 0x03, 0xe8, 0xf2, 0x55, 0xb6, 0x20, 0x0b, 0x7f, 0x73, 0x34, 0xfc,
	0xe5, 0xb5, 0x21, 0xdf, 0x40, 0x6a, 0x85, 0xcb, 0x37, 0x90, 0x4c, 0x0a, 0xde, 0x1d, 0xf6, 0x6b,
	0xb2, 0xe4, 0x0d, 0xb8, 0xea, 0xaa, 0x9a, 0xd6, 0x16, 0x6b, 0x9a, 0xe1, 0x73, 0x92, 0x61, 0x7e,
	0xa1, 0x2e, 0x59, 0x9a, 0x87, 0xe4, 0xe1, 0x98, 0xa0, 0x2c, 0x15, 0x98, 0x6b, 0x51, 0xc9, 0x8a,
	0xc9, 0x83, 0x7b, 0x88, 0xa7, 0x26, 0x0f, 0x2e, 0x16, 0x3b, 0xc8, 0xe3, 0x17, 0x57, 0xc9, 0x14,
	0x52, 0x94, 0x2f, 0x49, 0xcd, 0x43, 0x09, 0x6e, 0x08, 0xce, 0xb2, 0x93, 0x19, 0x4b, 0x41, 0x8f,
	0x64, 0x09, 0x6c, 0xd9, 0xd3, 0x47, 0xe8, 0xff, 0x33, 0x96, 0xb4, 0x12, 0x7c, 0x4e, 0x67, 0xad,
	0x4b, 0x92, 0xa7, 0x64, 0xde, 0x62, 0x97, 0x17, 0x9c, 0x67, 0xad, 0x82, 0xcd, 0x2e, 0x09, 0x97,
	0xdb, 0xfa, 0xd3, 0x0d, 0xf1, 0x12, 0x7f, 0x33, 0x9d, 0xd6, 0x05, 0xdf, 0xfd, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x10, 0x25, 0x4c, 0x0c, 0x9b, 0x0f, 0x00, 0x00,
}
